import type { Editor } from "../kernel/editor"

/**
 * Default GNU Emacs keybindings. Same API as user config (`editor.key` / `editor.defineKey`).
 * Customize by exporting `install(editor)` from `~/.jemacs/init.ts` and rebinding after defaults load.
 */
export function bindDefaultKeybindings(editor: Editor): void {
  bindGlobalKeys(editor)
  bindMinibufferKeys(editor)
}

function bindGlobalKeys(editor: Editor): void {
  editor.key("left", "backward-char")
  editor.key("right", "forward-char")
  editor.key("up", "previous-line")
  editor.key("down", "next-line")
  editor.key("backspace", "delete-backward-char")
  editor.key("delete", "delete-char")
  editor.key("return", "newline")
  editor.key("enter", "newline")

  editor.key("C-x C-x", "exchange-point-and-mark")
  editor.key("C-x C-s", "save-buffer")
  editor.key("C-x C-f", "find-file")
  editor.key("C-x b", "switch-to-buffer")
  editor.key("C-x C-b", "list-buffers")
  editor.key("C-x C-e", "eval-region")
  editor.key("C-x C-c", "save-buffers-kill-terminal")
  editor.key("C-x C-j", "previous-buffer")
  editor.key("C-x C-l", "next-buffer")
  editor.key("C-x C-r", "revert-buffer")
  editor.key("C-x f", "fzf-git")
  editor.key("C-x o", "other-window")
  editor.key("C-x 4 C-f", "find-file-other-window")
  editor.key("C-x 4 f", "find-file-other-window")
  editor.key("C-x 4 b", "switch-to-buffer-other-window")
  editor.key("C-x 4 C-o", "display-buffer-other-window")
  editor.key("C-M-v", "scroll-other-window")
  editor.key("M-C-v", "scroll-other-window-down")
  editor.key("C-space", "set-mark-command")
  editor.key("C-u", "universal-argument")
  editor.key("M--", "negative-argument")
  editor.key("C-g", "keyboard-quit")
  editor.key("C-s", "isearch-forward")
  editor.key("C-r", "isearch-backward")
  editor.key("C-f", "forward-char")
  editor.key("C-b", "backward-char")
  editor.key("C-n", "next-line")
  editor.key("C-p", "previous-line")
  editor.key("C-v", "scroll-up-command")
  editor.key("M-v", "scroll-down-command")
  editor.key("C-a", "move-beginning-of-line")
  editor.key("C-e", "move-end-of-line")
  editor.key("M-f", "forward-word")
  editor.key("M-b", "backward-word")
  editor.key("M-backspace", "backward-kill-word")
  editor.key("M-h", "backward-kill-word")
  editor.key("M-d", "kill-word")
  editor.key("esc f", "forward-word")
  editor.key("esc b", "backward-word")
  editor.key("esc d", "kill-word")
  editor.key("esc backspace", "backward-kill-word")
  editor.key("C-m", "newline")
  editor.key("C-j", "newline-and-indent")
  editor.key("tab", "indent-for-tab-command")
  editor.key("C-i", "indent-for-tab-command")
  editor.key("C-d", "delete-char")
  editor.key("C-k", "kill-line")
  editor.key("C-w", "kill-region")
  editor.key("M-w", "kill-ring-save")
  editor.key("C-y", "yank")
  editor.key("C-_", "undo")
  editor.key("M-x", "execute-extended-command")
  editor.key("esc x", "execute-extended-command")
  editor.key("C-h e", "view-echo-area-messages")
  editor.key("C-h b", "describe-bindings")
  editor.key("C-h c", "describe-mode")
  editor.key("C-h k", "describe-key")
  editor.key("C-x d", "dired")
  editor.key("C-c r", "replace-string")
  editor.key("C-c d", "point-to-register")
  editor.key("C-c C-d", "jump-to-register")
  editor.key("C-c g l", "git-link")
  editor.key("C-c g m", "magit-find-main")
  editor.key("C-c p", "projectile-command-map")
  editor.key("C-c SPC", "ace-jump-word-mode")
  editor.key("C-c C-x SPC", "ace-jump-char-mode")
  editor.key("C-c RET", "yafolding-toggle-element")
  editor.key("C-c t", "lsp-find-definition")
  editor.key("C-c C-t", "lsp-ui-peek-find-implementation")
  editor.key("C-x C-a", "lsp-execute-code-action")
  editor.key("C-\\", "tiling-cycle")
  // GNU Emacs: C-tab → other-window; C-S-tab → (other-window -1). Also accept common terminal names.
  for (const key of ["C-tab"]) editor.key(key, "other-window")
  for (const key of ["C-S-tab", "C-S-iso-lefttab", "C-iso-lefttab", "C-backtab"]) {
    editor.key(key, "other-window-backward")
  }
  editor.key("C-M-tab", "tab-bar-switch-to-next-tab")
  editor.key("C-M-S-tab", "tab-bar-switch-to-prev-tab")
  editor.key("s-}", "tab-bar-switch-to-next-tab")
  editor.key("s-{", "tab-bar-switch-to-prev-tab")
  editor.key("s-t", "tab-bar-new-tab")
  editor.key("s-w", "tab-bar-close-tab")
  editor.key("s-f", "counsel-ag")
  editor.key("s-m", "gptel-menu")
  editor.key("s-g", "gptel")
  editor.key("s-r", "restart-emacs")
  editor.key("C-c C-l", "load-plugin")
  editor.key("C-c C-r", "reload-current-file")
  editor.key("C-c C-q", "save-buffers-kill-terminal")

  editor.key("C-/", "undo")
  editor.key("C-@", "set-mark-command")
  editor.key("M-y", "yank-pop")
  editor.key("C-q", "quoted-insert")
  editor.key("C-t", "transpose-chars")
  editor.key("C-o", "open-line")
  editor.key("C-l", "recenter-top-bottom")
  editor.key("M-<", "beginning-of-buffer")
  editor.key("M->", "end-of-buffer")
  editor.key("M-%", "query-replace")
  editor.key("C-x C-w", "write-file")
  editor.key("C-x C-v", "find-alternate-file")
  editor.key("C-x k", "kill-buffer")
  editor.key("C-x 0", "delete-window")
  editor.key("C-x 1", "delete-other-windows")
  editor.key("C-x 2", "split-window-below")
  editor.key("C-x 3", "split-window-right")
  editor.key("C-x u", "undo")
  editor.key("C-x h", "mark-whole-buffer")
  editor.key("C-x l", "count-lines-page")
  editor.key("M-g g", "goto-line")
  // M-. and xref history: installXref (after LSP).
  editor.key("C-x r SPC", "point-to-register")
  editor.key("C-x r j", "jump-to-register")
  editor.key("C-x r w", "window-configuration-to-register")
  editor.key("C-x r k", "kill-rectangle")
  editor.key("C-x r y", "yank-rectangle")
  editor.key("C-x (", "start-kbd-macro")
  editor.key("C-x )", "end-kbd-macro")
  editor.key("C-x e", "call-last-kbd-macro")
  editor.key("C-h f", "describe-function")
  editor.key("C-M-x", "eval-defun")
  editor.key("C-h v", "describe-variable")
  editor.key("C-h a", "apropos-command")
  editor.key("C-h i", "info")
  editor.key("C-h C-h", "help-for-help")
}

function bindMinibufferKeys(editor: Editor): void {
  editor.defineKey("minibuffer", "tab", "minibuffer-complete")
  editor.defineKey("minibuffer", "C-i", "minibuffer-complete")
  editor.defineKey("minibuffer", "enter", "exit-minibuffer")
  editor.defineKey("minibuffer", "C-m", "exit-minibuffer")
  editor.defineKey("minibuffer", "return", "exit-minibuffer")
  editor.defineKey("minibuffer", "esc", "abort-recursive-edit")
  editor.defineKey("minibuffer", "backspace", "delete-backward-char")
  editor.defineKey("minibuffer", "up", "previous-history-element")
  editor.defineKey("minibuffer", "down", "next-history-element")
  editor.defineKey("minibuffer", "C-u", "universal-argument")
  editor.defineKey("minibuffer", "M--", "negative-argument")
  editor.defineKey("minibuffer", "C-g", "keyboard-quit")
}
