import { mkdir, readFile, writeFile } from "node:fs/promises"
import { homedir } from "node:os"
import { dirname, join } from "node:path"
import type { Editor } from "../kernel/editor"
import type { Evaluator } from "../runtime/evaluator"
import { getCustom, getCustomIcon, listCustomIcons, listCustomVariables } from "../runtime/custom"
import { getCustomFace, listKnownFaceNames } from "../runtime/faces"
import { enableBuiltinTheme, getBuiltinTheme, listEnabledBuiltinThemes, listSavedBuiltinThemes, saveEnabledBuiltinThemes } from "../themes"

/** Emacs `custom-file`: where `custom-save-all` writes. `JEMACS_CUSTOM_FILE`
 *  overrides it so tests never clobber the real user file. */
export function customFilePath(): string {
  return process.env.JEMACS_CUSTOM_FILE
    ?? getCustom<string>("custom-file")
    ?? join(homedir(), ".jemacs", "custom.ts")
}

export async function loadCustomFile(editor: Editor, evaluator: Evaluator): Promise<void> {
  const path = customFilePath()
  try {
    const source = await readFile(path, "utf8")
    await evaluator.eval(source, path)
    // `custom-enabled-themes` is an ordinary saved option, so restoring it is
    // what re-enables the themes; `custom-theme-save` is the writer.
    for (const name of getCustom<string[]>("custom-enabled-themes") ?? []) {
      if (getBuiltinTheme(name)) enableBuiltinTheme(name)
    }
    saveEnabledBuiltinThemes()
    const active = listEnabledBuiltinThemes().at(-1)
    if (active) {
      const theme = getBuiltinTheme(active)
      if (theme) editor.setTheme(theme)
    }
    editor.refreshComposedTheme()
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error
  }
}

/** `custom-save-all`: rewrite the custom file from the current saved values.
 *  Layout mirrors cus-edit.el: themes, then `customSetVariables`, then
 *  `customSetFaces`, each a single generated form. */
export async function saveCustomFile(): Promise<void> {
  const path = customFilePath()
  await mkdir(dirname(path), { recursive: true })
  const lines = [
    "// Generated by Custom — edits may be overwritten.",
    "",
  ]
  for (const theme of listSavedBuiltinThemes()) {
    lines.push(`enableBuiltinTheme(${JSON.stringify(theme)})`)
  }

  const savedVariables = listCustomVariables().filter(variable => variable.savedValue !== undefined)
  if (savedVariables.length) {
    lines.push("customSetVariables(")
    for (const variable of savedVariables) {
      const comment = variable.savedComment
      lines.push(comment
        ? `  [${JSON.stringify(variable.name)}, ${JSON.stringify(variable.savedValue)}, ${JSON.stringify(comment)}],`
        : `  [${JSON.stringify(variable.name)}, ${JSON.stringify(variable.savedValue)}],`)
    }
    lines.push(")")
  }

  // The `default` face must come first: the others inherit its font metrics.
  const savedFaces = listKnownFaceNames()
    .filter(name => getCustomFace(name)?.savedSpec)
    .sort((a, b) => (a === "default" ? -1 : b === "default" ? 1 : a.localeCompare(b)))
  if (savedFaces.length) {
    lines.push("customSetFaces(")
    for (const name of savedFaces) {
      const face = getCustomFace(name)!
      lines.push(face.savedComment
        ? `  [${JSON.stringify(name)}, ${JSON.stringify(face.savedSpec)}, ${JSON.stringify(face.savedComment)}],`
        : `  [${JSON.stringify(name)}, ${JSON.stringify(face.savedSpec)}],`)
    }
    lines.push(")")
  }

  // `custom-save-icons`.
  const savedIcons = listCustomIcons().filter(icon => icon.savedSpec)
  if (savedIcons.length) {
    lines.push("customSetIcons(")
    for (const icon of savedIcons) {
      lines.push(`  [${JSON.stringify(icon.name)}, ${JSON.stringify(icon.savedSpec)}],`)
    }
    lines.push(")")
  }

  if (lines.at(-1) !== "") lines.push("")
  await writeFile(path, lines.join("\n"), "utf8")
}
