/**
 * Generate TypeScript from Emacs lsp-protocol.el (lsp-interface + autogenerated enums).
 * Source: Emacs ELPA lsp-mode package lsp-protocol.el
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname, join } from "node:path"

const elPath = process.env.LSP_PROTOCOL_EL
  ?? `${process.env.HOME}/.emacs.d/elpa/lsp-mode-20240529.2057/lsp-protocol.el`
const outDir = join(import.meta.dir, "../src/lsp/lsp-protocol/generated")

function parseFields(raw: string): string[] {
  if (!raw || raw === "nil") return []
  return raw
    .replace(/[():]/g, " ")
    .split(/\s+/)
    .filter(Boolean)
    .map(f => f.replace(/^:/, ""))
}

function splitTopLevelGroups(rest: string): [string, string] | null {
  if (rest.startsWith("nil")) {
    const afterNil = rest.slice(3).trim()
    if (afterNil.startsWith("(")) {
      const close = findMatchingParen(afterNil, 0)
      if (close === -1) return null
      return ["", afterNil.slice(1, close)]
    }
    return ["", ""]
  }
  if (!rest.startsWith("(")) return null
  const close1 = findMatchingParen(rest, 0)
  if (close1 === -1) return null
  const first = rest.slice(1, close1)
  let tail = rest.slice(close1 + 1).trim()
  if (tail.startsWith("nil")) {
    if (tail === "nil") return [first, ""]
    const close2 = findMatchingParen(tail, tail.indexOf("("))
    if (close2 === -1) return [first, ""]
    return [first, tail.slice(tail.indexOf("(") + 1, close2)]
  }
  if (!tail.startsWith("(")) return null
  const close2 = findMatchingParen(tail, 0)
  if (close2 === -1) return null
  return [first, tail.slice(1, close2)]
}

function findMatchingParen(s: string, openIndex: number): number {
  let depth = 0
  for (let i = openIndex; i < s.length; i++) {
    if (s[i] === "(") depth++
    else if (s[i] === ")") {
      depth--
      if (depth === 0) return i
    }
  }
  return -1
}

function parseInterfaceBlock(block: string, interfaces: Array<{ name: string; required: string[]; optional: string[] }>): void {
  for (const line of block.split("\n")) {
    const trimmed = line.trim()
    if (!trimmed.startsWith("(") || trimmed.startsWith("(lsp-interface")) continue
    const inner = trimmed.slice(1, trimmed.endsWith(")") ? -1 : undefined)
    const nameEnd = inner.search(/\s/)
    if (nameEnd === -1) continue
    const name = inner.slice(0, nameEnd).trim()
    const groups = splitTopLevelGroups(inner.slice(nameEnd).trim())
    if (!groups) continue
    interfaces.push({
      name,
      required: parseFields(groups[0]),
      optional: parseFields(groups[1]),
    })
  }
}

function parseInterfaces(el: string): Array<{ name: string; required: string[]; optional: string[] }> {
  const interfaces: Array<{ name: string; required: string[]; optional: string[] }> = []
  const re = /\(lsp-interface\b/g
  let m: RegExpExecArray | null
  while ((m = re.exec(el))) {
    const open = m.index
    const close = findMatchingParen(el, open)
    if (close === -1) continue
    parseInterfaceBlock(el.slice(open, close + 1), interfaces)
  }
  const seen = new Set<string>()
  return interfaces.filter(i => {
    if (seen.has(i.name)) return false
    seen.add(i.name)
    return true
  })
}

function parseEnums(el: string): Array<{ constName: string; value: number; label: string }> {
  const start = el.indexOf(";; begin autogenerated code")
  const end = el.indexOf("(lsp-interface\n (CallHierarchyCapabilities", start)
  const block = el.slice(start, end)
  const enums: Array<{ constName: string; value: number; label: string }> = []
  const re = /\(defconst (lsp\/[^\s]+) (\d+)\)/g
  let m: RegExpExecArray | null
  while ((m = re.exec(block))) {
    const constName = m[1]!
    const value = Number(m[2])
    const label = constName.split("/").pop()!.replace(/-/g, " ").replace(/\b\w/g, c => c.toUpperCase()).replace(/\s/g, "")
    enums.push({ constName, value, label })
  }
  return enums
}

function parseLookups(el: string): Array<{ varName: string; labels: string[] }> {
  const start = el.indexOf(";; begin autogenerated code")
  const end = el.indexOf("(lsp-interface\n (CallHierarchyCapabilities", start)
  const block = el.slice(start, end)
  const lookups: Array<{ varName: string; labels: string[] }> = []
  const re = /\(defvar (lsp\/[^\s]+-lookup)\s+\[([^\]]*)\]\)/g
  let m: RegExpExecArray | null
  while ((m = re.exec(block))) {
    const labels = m[2]!
      .split(/\s+/)
      .map(s => s.trim())
      .filter(s => s && s !== "nil")
    lookups.push({ varName: m[1]!, labels })
  }
  return lookups
}

function toCamel(name: string): string {
  return name.replace(/:./g, s => s[1]!.toUpperCase()).replace(/[-.](\w)/g, (_, c) => c.toUpperCase())
}

function builderName(iface: string): string {
  return `lspMake${iface.replace(/[:.-]/g, "")}`
}

function guardName(iface: string): string {
  return `lsp${iface.replace(/[:.-]/g, "")}P`
}

const el = readFileSync(elPath, "utf8")
const interfaces = parseInterfaces(el)
const enums = parseEnums(el)
const lookups = parseLookups(el)

mkdirSync(outDir, { recursive: true })

function elispConstToTs(name: string): string {
  return name.replace(/\//g, "_").replace(/-/g, "_")
}

const enumsTs = `/** Autogenerated from lsp-protocol.el — do not edit by hand. Run: bun run scripts/generate-lsp-protocol.ts */
${enums.map(e => `export const ${elispConstToTs(e.constName)} = ${e.value} as const`).join("\n")}

${lookups.map(l => {
  const tsName = elispConstToTs(l.varName)
  const entries = ["null", ...l.labels.map(label => `"${label}"`)].join(", ")
  return `export const ${tsName}: readonly (string | null)[] = [${entries}]`
}).join("\n\n")}
`

const builderBlocks = interfaces.map(iface => {
  const req = iface.required.map(f => `${f}: unknown`)
  const opt = iface.optional.map(f => `${f}?: unknown`)
  const params = [...req, ...opt].join("; ")
  const checks = iface.required.length
    ? iface.required.map(f => `("${f}" in o)`).join(" && ")
    : "true"
  return [
    `// Construct ${iface.name}`,
    `export function ${builderName(iface.name)}(args: { ${params} } & AnyRecord): AnyRecord {`,
    "  return { ...args }",
    "}",
    "",
    `export function ${guardName(iface.name)}(value: unknown): value is AnyRecord {`,
    '  if (value == null || typeof value !== "object") return false',
    "  const o = value as AnyRecord",
    `  return ${checks}`,
    "}",
  ].join("\n")
})

const buildersTs = [
  "// Autogenerated from lsp-protocol.el — run: bun run scripts/generate-lsp-protocol.ts",
  "",
  "type AnyRecord = Record<string, unknown>",
  "",
  ...builderBlocks,
  "",
].join("\n")

const registryTs = `/** Interface registry mirroring lsp-protocol.el lsp-interface block. */
export const lspProtocolInterfaces = ${JSON.stringify(interfaces.map(i => i.name), null, 2)} as const
export type LspProtocolInterfaceName = typeof lspProtocolInterfaces[number]
`

writeFileSync(join(outDir, "enums.ts"), enumsTs)
writeFileSync(join(outDir, "builders.ts"), buildersTs)
writeFileSync(join(outDir, "registry.ts"), registryTs)

console.log(`Generated ${interfaces.length} interfaces, ${enums.length} enum constants, ${lookups.length} lookups -> ${outDir}`)
